parametros[0]=0;//cantidad zoombies
parametros[1]=6;//vida maxima
parametros[2]=12;//velocidad maxima
parametros[3]=8;//municion maxima
parametros[4]=40;//velocidad de flechas
parametros[5]=18;//tiempo existencia de flechas
parametros[6]=20;//tiempo cambio movimiento random
parametros[7]=500;//distancia visualizacion
parametros[8]=0.9;//fraccion para disparo
parametros[9]=0.3;//fraccion minima a enemigo
parametros[10]=0.8;//fraccion maxima a enemigo
parametros[11]=0.6;//fraccion en recarga
parametros[12]=30;//angulo huida
parametros[13]=10;//angulo errar tiro
parametros[14]=0.6;//velocidad entretiros
parametros[15]=1.3;//velocidad recarga
parametros[16]=1;//recompensa vida
parametros[17]=0;//equilibrio muertes
parametros[18]=1;//gana grupo vs bombas
parametros[19]=1;//manchas suelo
parametros[20]=0;//ir al centro
parametros[21]=0;//ia agrupada
