resultado=false;
if(keyboard_lastchar!=""){
    keyboard_lastchar=string_lower(keyboard_lastchar);
    if(keyboard_lastchar=" "){
        keyboard_lastchar="_";}
    else if(keyboard_lastchar="Ñ"){
        keyboard_lastchar="ñ";}
switch(keyboard_lastchar){
    case "a": resultado=true; break;
    case "b": resultado=true; break;
    case "c": resultado=true; break;
    case "d": resultado=true; break;
    case "e": resultado=true; break;
    case "f": resultado=true; break;
    case "g": resultado=true; break;
    case "h": resultado=true; break;
    case "i": resultado=true; break;
    case "j": resultado=true; break;
    case "k": resultado=true; break;
    case "l": resultado=true; break;
    case "m": resultado=true; break;
    case "n": resultado=true; break;
    case "ñ": resultado=true; break;
    case "o": resultado=true; break;
    case "p": resultado=true; break;
    case "q": resultado=true; break;
    case "r": resultado=true; break;
    case "s": resultado=true; break;
    case "t": resultado=true; break;
    case "u": resultado=true; break;
    case "v": resultado=true; break;
    case "w": resultado=true; break;
    case "x": resultado=true; break;
    case "y": resultado=true; break;
    case "z": resultado=true; break;
    case "0": resultado=true; break;
    case "1": resultado=true; break;
    case "2": resultado=true; break;
    case "3": resultado=true; break;
    case "4": resultado=true; break;
    case "5": resultado=true; break;
    case "6": resultado=true; break;
    case "7": resultado=true; break;
    case "8": resultado=true; break;
    case "9": resultado=true; break;
    case "_": resultado=true; break;
    case ".": resultado=true; break;
    case "-": resultado=true; break;}}
return(resultado);
